Use Sprixels in pgl-editor item wizard. Add serialization/deseralization to Sprixels in _ref2obj and _obj2ref
arnauddupuis/pygamelib pull request #114
Opened 2020-10-07 21:10 UTC by ollelogdahl

## Description

Added setting items sprixel in item wizard for `pgl-editor`. The model picker looks the same, only resulting in also setting the items sprixel. Items model is still set, to maintain backwards compatability. Also added sprixel encoding and decoding in `_ref2obj` and `_obj2ref`. Function `_ref2obj` is using the `Sprixel.from_ansi()` function. This also fixed the `load_board()` and `save_board()` functions, requested in the issue.

Fixes #110 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Ran the editor and made sure the changes worked corretly.

**Test Configuration**:
* OS: Linux
* OS version: 5.4.61-1
* Python version: 3.8.5
* Architecture: amd64

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-10-08 08:46 UTC, arnauddupuis commented
I did a first quick review and it looks good! Thanks!
I did not have a lot of time today, I'll do the real review tomorrow.

2020-10-09 01:15 UTC, arnauddupuis requested changes
So I tested your changes and when saving there is a small issue ;)
```bash
Traceback (most recent call last):
  File "./pgl-editor.py", line 1059, in <module>
    save_current_board()
  File "./pgl-editor.py", line 648, in save_current_board
    game.save_board(1, current_file)
  File "/home/arnaud/Code/Python/PyGameLib/contrib_reviews/ollelogdahl-pygamelib/pygamelib/engine.py", line 2466, in save_board
    json.dump(data, f)
  File "/usr/lib64/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib64/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib64/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  [Previous line repeated 1 more time]
  File "/usr/lib64/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib64/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Sprixel is not JSON serializable
```
The issue comes from Game._obj2ref(): you need to use Sprixel.serialize() to convert a sprixel into a dict.
The documentation is here: https://pygamelib.readthedocs.io/en/latest/gfx_core.html#pygamelib.gfx.core.Sprixel.serialize
I'll point the specifics in the code review.

2020-10-09 01:17 UTC, arnauddupuis commented on pygamelib/engine.py
> +            "sprixel": obj.sprixel,
Actually the fix is pretty simple: just use `obj.sprixel.serialize()` instead of `obj.sprixel`.

2020-10-09 01:21 UTC, arnauddupuis commented on pygamelib/engine.py
> +                local_object.sprixel = core.Sprixel.from_ansi(ref["sprixel"])
If you use `Sprixel.serialize()` you need need to use `Sprixel.load()` here (https://pygamelib.readthedocs.io/en/latest/gfx_core.html#pygamelib.gfx.core.Sprixel.load).
From ansi does not load a serialized sprixel (it loads an ANSI sequence like the one generated by the climage python module).

2020-10-09 07:32 UTC, ollelogdahl commented
Ok i got that. Thanks you for helping me! :)

2020-10-09 18:06 UTC, arnauddupuis commented
Great, thanks a lot for your help. I will put more issues on that topic because this is all preparatory work for the sprite editor.
I'll review your changes later today.
If you want to discuss this issue or others do not hesitate to join the Discord server (link in the README_HACKTOBERFEST.md file).

2020-10-09 23:33 UTC, arnauddupuis approved these changes
All good, thanks a lot!
Testing your code I realized that there's a bug in the code that manages the pseudo-transparency (change of background color).

2020-10-10 00:06 UTC, merged

2020-10-10 00:09 UTC, arnauddupuis commented
@ollelogdahl you forgot to add tests coverage and the overall coverage score lowered.
Would you be able to add the tests required?

2020-10-10 09:40 UTC, ollelogdahl commented
I Would gladly help. Only this is that im unsure of how to write coverage tests (done some unittesting before). I'll take a look at all current tests, and see if i can put something together!

2020-10-10 10:09 UTC, ollelogdahl commented
So what exactly needs to be tested? sprixel.serialize and sprixel.load?

2020-10-10 19:40 UTC, arnauddupuis commented
No, it's very simple: when you added the code for the sprixel, you added a if statement. Codecov needs to see that statement executed in the test suite.
I added issue #126, I'll do the code and add you as a reviewer of the PR.